/*
 * RankVectors API
 *
 * Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Credit-Based System**: Pay-per-use model with transparent pricing - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage credits  ## Authentication All API endpoints require authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys 
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support@rankvectors.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreditBalanceInfo {
    /// Project identifier
    #[serde(rename = "projectId")]
    pub project_id: String,
    /// Total credits purchased
    #[serde(rename = "creditsTotal")]
    pub credits_total: f64,
    /// Credits consumed
    #[serde(rename = "creditsUsed")]
    pub credits_used: f64,
    /// Credits remaining
    #[serde(rename = "creditsRemaining")]
    pub credits_remaining: f64,
    /// Last credit reset timestamp
    #[serde(rename = "lastResetAt", skip_serializing_if = "Option::is_none")]
    pub last_reset_at: Option<String>,
}

impl CreditBalanceInfo {
    pub fn new(project_id: String, credits_total: f64, credits_used: f64, credits_remaining: f64) -> CreditBalanceInfo {
        CreditBalanceInfo {
            project_id,
            credits_total,
            credits_used,
            credits_remaining,
            last_reset_at: None,
        }
    }
}

