/*
 * RankVectors API
 *
 * Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Page-Based Plans**: Predictable pricing by number of pages monitored - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage page usage and limits  ## Authentication Most API endpoints support authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys  **Note**: Some endpoints (marked in the documentation) support both API key authentication and web session authentication (Stack Auth).  API key authentication is required for SDK usage and external integrations like WordPress plugins. 
 *
 * The version of the OpenAPI document: 1.3.1
 * Contact: tj@rankvectors.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PageChange {
    /// Change identifier
    #[serde(rename = "id")]
    pub id: String,
    /// Page identifier
    #[serde(rename = "pageId")]
    pub page_id: String,
    /// Project identifier
    #[serde(rename = "projectId")]
    pub project_id: String,
    /// Change status
    #[serde(rename = "changeStatus")]
    pub change_status: ChangeStatus,
    /// Page visibility
    #[serde(rename = "visibility")]
    pub visibility: Visibility,
    /// Previous scrape timestamp
    #[serde(rename = "previousScrapeAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub previous_scrape_at: Option<Option<String>>,
    /// Current scrape timestamp
    #[serde(rename = "currentScrapeAt")]
    pub current_scrape_at: String,
    #[serde(rename = "page", skip_serializing_if = "Option::is_none")]
    pub page: Option<Box<models::PageChangePage>>,
}

impl PageChange {
    pub fn new(id: String, page_id: String, project_id: String, change_status: ChangeStatus, visibility: Visibility, current_scrape_at: String) -> PageChange {
        PageChange {
            id,
            page_id,
            project_id,
            change_status,
            visibility,
            previous_scrape_at: None,
            current_scrape_at,
            page: None,
        }
    }
}
/// Change status
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ChangeStatus {
    #[serde(rename = "new")]
    New,
    #[serde(rename = "same")]
    Same,
    #[serde(rename = "changed")]
    Changed,
    #[serde(rename = "removed")]
    Removed,
}

impl Default for ChangeStatus {
    fn default() -> ChangeStatus {
        Self::New
    }
}
/// Page visibility
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Visibility {
    #[serde(rename = "visible")]
    Visible,
    #[serde(rename = "hidden")]
    Hidden,
    #[serde(rename = "error")]
    Error,
}

impl Default for Visibility {
    fn default() -> Visibility {
        Self::Visible
    }
}

