/*
 * RankVectors API
 *
 * Intelligent internal linking optimization API using AI.   RankVectors helps you automatically discover and implement optimal internal links  across your website to improve SEO performance and user experience.  ## Key Features - **AI-Powered Analysis**: Uses OpenAI embeddings to find optimal linking opportunities - **Smart Crawling**: Automatically crawls and analyzes your website content - **Automated Implementation**: Implement links via webhooks or manual instructions - **Page-Based Plans**: Predictable pricing by number of pages monitored - **Multi-Platform Support**: Works with any CMS or platform via REST API  ## Getting Started 1. Create a project with your website URL 2. Start a crawl to analyze your content 3. Generate AI-powered link suggestions 4. Implement suggestions via API or webhook 5. Track performance and manage page usage and limits  ## Authentication Most API endpoints support authentication using your RankVectors API key. Include your API key in the `Authorization` header: ``` Authorization: Bearer YOUR_API_KEY ```  Get your API key from your RankVectors dashboard: Settings → API Keys  **Note**: Some endpoints (marked in the documentation) support both API key authentication and web session authentication (Stack Auth).  API key authentication is required for SDK usage and external integrations like WordPress plugins. 
 *
 * The version of the OpenAPI document: 1.3.1
 * Contact: tj@rankvectors.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectAnalytics {
    #[serde(rename = "implementationStats")]
    pub implementation_stats: Box<models::ProjectAnalyticsImplementationStats>,
    #[serde(rename = "suggestionStats")]
    pub suggestion_stats: Box<models::ProjectAnalyticsSuggestionStats>,
    #[serde(rename = "syncStats")]
    pub sync_stats: Box<models::ProjectAnalyticsSyncStats>,
    #[serde(rename = "contentStats")]
    pub content_stats: Box<models::ProjectAnalyticsContentStats>,
    #[serde(rename = "topSourcePages", skip_serializing_if = "Option::is_none")]
    pub top_source_pages: Option<Vec<serde_json::Value>>,
    #[serde(rename = "topTargetPages", skip_serializing_if = "Option::is_none")]
    pub top_target_pages: Option<Vec<serde_json::Value>>,
    #[serde(rename = "orphanedPages", skip_serializing_if = "Option::is_none")]
    pub orphaned_pages: Option<Vec<serde_json::Value>>,
    #[serde(rename = "highPerformingPages", skip_serializing_if = "Option::is_none")]
    pub high_performing_pages: Option<Vec<serde_json::Value>>,
    #[serde(rename = "mostSuggestedPages", skip_serializing_if = "Option::is_none")]
    pub most_suggested_pages: Option<Vec<serde_json::Value>>,
    #[serde(rename = "mostLinkedToPages", skip_serializing_if = "Option::is_none")]
    pub most_linked_to_pages: Option<Vec<serde_json::Value>>,
    #[serde(rename = "recentImplementations", skip_serializing_if = "Option::is_none")]
    pub recent_implementations: Option<Vec<models::Implementation>>,
    #[serde(rename = "recentSuggestions", skip_serializing_if = "Option::is_none")]
    pub recent_suggestions: Option<Vec<models::Suggestion>>,
    #[serde(rename = "recentSyncs", skip_serializing_if = "Option::is_none")]
    pub recent_syncs: Option<Vec<serde_json::Value>>,
}

impl ProjectAnalytics {
    pub fn new(implementation_stats: models::ProjectAnalyticsImplementationStats, suggestion_stats: models::ProjectAnalyticsSuggestionStats, sync_stats: models::ProjectAnalyticsSyncStats, content_stats: models::ProjectAnalyticsContentStats) -> ProjectAnalytics {
        ProjectAnalytics {
            implementation_stats: Box::new(implementation_stats),
            suggestion_stats: Box::new(suggestion_stats),
            sync_stats: Box::new(sync_stats),
            content_stats: Box::new(content_stats),
            top_source_pages: None,
            top_target_pages: None,
            orphaned_pages: None,
            high_performing_pages: None,
            most_suggested_pages: None,
            most_linked_to_pages: None,
            recent_implementations: None,
            recent_suggestions: None,
            recent_syncs: None,
        }
    }
}

